### ISSUE TITLE
CT setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-intro#102]
Also in mixed numbers
```
fractions-intro : fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/fractions-intro/fractions-intro_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/assert/js/assert.js:22:13)
    at VBox.setCenterY (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:2725:15)
    at VBox.set centerY [as centerY] (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:2731:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:5145:23
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/sherpa/lib/lodash-4.17.4.js:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/sherpa/lib/lodash-4.17.4.js:9359:14)
    at VBox.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:5132:7)
    at VBox.LayoutBox [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/LayoutBox.js:104:8)
    at new VBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/VBox.js:30:13)
    at new ShapeGroupNode (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/fractions-common/js/building/view/ShapeGroupNode.js:134:27)
id: Bayes Chrome
Approximately 4/13/2020, 12:19:27 AM
fractions-intro : fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/fractions-intro/fractions-intro_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/assert/js/assert.js:22:13)
    at VBox.setCenterY (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:2725:15)
    at VBox.set centerY [as centerY] (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:2731:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:5145:23
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/sherpa/lib/lodash-4.17.4.js:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/sherpa/lib/lodash-4.17.4.js:9359:14)
    at VBox.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:5132:7)
    at VBox.LayoutBox [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/LayoutBox.js:104:8)
    at new VBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/VBox.js:30:13)
    at new ShapeGroupNode (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/fractions-common/js/building/view/ShapeGroupNode.js:134:27)
id: Bayes Chrome
Approximately 4/13/2020, 12:19:27 AM
fractions-intro : xss-fuzz : load
https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/fractions-intro/fractions-intro_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/assert/js/assert.js:22:13)
    at VBox.setCenterY (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:2725:15)
    at VBox.set centerY [as centerY] (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:2731:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:5145:23
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/sherpa/lib/lodash-4.17.4.js:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/sherpa/lib/lodash-4.17.4.js:9359:14)
    at VBox.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:5132:7)
    at VBox.LayoutBox [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/LayoutBox.js:104:8)
    at new VBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/VBox.js:30:13)
    at new ShapeGroupNode (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/fractions-common/js/building/view/ShapeGroupNode.js:134:27)
id: Bayes Chrome
Approximately 4/13/2020, 12:19:27 AM
fractions-intro : xss-fuzz : run
https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/fractions-intro/fractions-intro_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting centerY is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/assert/js/assert.js:22:13)
    at VBox.setCenterY (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:2725:15)
    at VBox.set centerY [as centerY] (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:2731:31)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:5145:23
    at arrayEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/sherpa/lib/lodash-4.17.4.js:537:11)
    at Function.forEach (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/sherpa/lib/lodash-4.17.4.js:9359:14)
    at VBox.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/Node.js:5132:7)
    at VBox.LayoutBox [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/LayoutBox.js:104:8)
    at new VBox (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/scenery/js/nodes/VBox.js:30:13)
    at new ShapeGroupNode (https://bayes.colorado.edu/continuous-testing/snapshot-1586758767496/fractions-common/js/building/view/ShapeGroupNode.js:134:27)
id: Bayes Chrome
Approximately 4/13/2020, 12:19:27 AM
```

**Comment by KatieWoe** [comment]
Also in build a fraction

**Comment by jonathanolson** [comment]
I believe the above commit should fix this.
