### ISSUE TITLE
Multitouch assertion: currentView.bucketNode is undefined

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/fractions-intro#103]
From https://github.com/phetsims/aqua/issues/106, the following was caught
```
fractions-intro
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (http://10.0.0.179:8080/assert/js/assert.js:22:13)
    at CircularSceneNode.getBucketPosition (http://10.0.0.179:8080/fractions-common/js/intro/view/ContainerSetScreenView.js:98:17)
    at http://10.0.0.179:8080/fractions-common/js/intro/view/CellSceneNode.js:222:54
    at DragListener.end [as _end] (http://10.0.0.179:8080/fractions-common/js/intro/view/PieceNode.js:81:18)
    at http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:344:25
    at DragListener.onRelease (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:621:17)
    at Action.execute (http://10.0.0.179:8080/axon/js/Action.js:225:18)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:418:25)
    at DragListener.release (http://10.0.0.179:8080/scenery/js/listeners/DragListener.js:340:37)
    at DragListener.interrupt (http://10.0.0.179:8080/scenery/js/listeners/PressListener.js:475:12)
```

**Comment by jessegreenberg** [comment]
From phetsims/aqua#106, assigning to the responsible dev for this repo.

**Comment by jessegreenberg** [comment]
This assertion is also being thrown in fractions-mixed-numbers, so likely not specific to intro.
