### ISSUE TITLE
CT: item not found in Array

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/fractions-intro#96]
```
fractions-intro : xss-fuzz : run
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/assert/js/assert.js:22:13)
    at arrayRemove (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/phet-core/js/arrayRemove.js?bust=1535711133611:22:15)
    at FractionChallengeNode.removeShapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/fractions-common/js/game/view/FractionChallengeNode.js?bust=1535711133611:345:7)
    at ObservableArray._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/axon/js/ObservableArray.js?bust=1535711133611:155:18)
    at ObservableArray.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/axon/js/ObservableArray.js?bust=1535711133611:195:14)
    at Animator.shapePiece.animator.animateTo [as endAnimationCallback] (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/fractions-common/js/building/model/BuildingModel.js?bust=1535711133611:149:32)
    at Animator.endAnimation (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/fractions-common/js/building/model/Animator.js?bust=1535711133611:111:14)
    at Animator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/fractions-common/js/building/model/Animator.js?bust=1535711133611:119:16)
    at ShapePiece.step (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/fractions-common/js/building/model/ShapePiece.js?bust=1535711133611:110:21)
    at activeShapePieces.forEach.shapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1535706556329/fractions-common/js/building/model/BuildingModel.js?bust=1535711133611:389:20)
Approximately 8/31/2018, 3:09:16 AM
```

**Comment by KatieWoe** [comment]
Error now reads:
```
fractions-intro : xss-fuzz : run
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
    at ObservableArray.push (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/axon/js/ObservableArray.js?bust=1536596688782:220:15)
    at BuildingLabModel.removeLastPieceFromShapeGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/fractions-common/js/building/model/BuildingModel.js?bust=1536596688782:243:34)
    at removeLastListener (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/fractions-common/js/building/view/BuildingLabScreenView.js?bust=1536596688782:264:22)
    at Array.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/fractions-common/js/building/view/ReturnButton.js?bust=1536596688782:48:9)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/axon/js/Emitter.js?bust=1536596688782:136:52)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/sun/js/buttons/PushButtonModel.js?bust=1536596688782:155:25)
    at Array.downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/sun/js/buttons/PushButtonModel.js?bust=1536596688782:88:16)
    at Emitter.emit2 (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/axon/js/Emitter.js?bust=1536596688782:182:52)
    at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/axon/js/Property.js?bust=1536596688782:304:29)
    at Property.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1536572626913/axon/js/Property.js?bust=1536596688782:287:14)
Approximately 9/10/2018, 3:43:46 AM
```

**Comment by KatieWoe** [comment]
Few other CT results showing up and documenting in this issue. @jonathanolson 
```
fractions-intro : fuzz : built : run
Uncaught TypeError: Cannot read property '_parents' of undefined
TypeError: Cannot read property '_parents' of undefined
    at t.removeChildWithIndex (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:448438)
    at t.removeChild (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:448251)
    at s.value (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:805624)
    at t._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:99589)
    at t.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:99843)
    at e.endAnimationCallback (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:161635)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:64567)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:64736)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:151299)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-intro/build/phet/fractions-intro_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz:1335:165979
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
fractions-intro : fuzz : require.js-canvas : run
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
    at ObservableArray.push (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/ObservableArray.js?bust=1540214747491:226:15)
    at BuildingLabModel.removeLastPieceFromShapeGroup (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-common/js/building/model/BuildingModel.js?bust=1540214747491:243:34)
    at removeLastListener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-common/js/building/view/BuildingLabScreenView.js?bust=1540214747491:264:22)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-common/js/building/view/ReturnButton.js?bust=1540214747491:48:9)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540214747491:187:53)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/sun/js/buttons/PushButtonModel.js?bust=1540214747491:155:25)
    at Array.downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/sun/js/buttons/PushButtonModel.js?bust=1540214747491:88:16)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Emitter.js?bust=1540214747491:258:52)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Property.js?bust=1540214747491:277:29)
    at BooleanProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/Property.js?bust=1540214747491:258:14)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
fractions-intro : xss-fuzz : run
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/assert/js/assert.js:22:13)
    at arrayRemove (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/phet-core/js/arrayRemove.js?bust=1540188362253:22:15)
    at FractionChallengeNode.removeShapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-common/js/game/view/FractionChallengeNode.js?bust=1540188362253:345:7)
    at ObservableArray._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/ObservableArray.js?bust=1540188362253:161:18)
    at ObservableArray.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/axon/js/ObservableArray.js?bust=1540188362253:201:14)
    at Animator.shapePiece.animator.animateTo [as endAnimationCallback] (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-common/js/building/model/BuildingModel.js?bust=1540188362253:149:32)
    at Animator.endAnimation (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-common/js/building/model/Animator.js?bust=1540188362253:111:14)
    at Animator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-common/js/building/model/Animator.js?bust=1540188362253:119:16)
    at ShapePiece.step (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-common/js/building/model/ShapePiece.js?bust=1540188362253:110:21)
    at activeShapePieces.forEach.shapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1540180835952/fractions-common/js/building/model/BuildingModel.js?bust=1540188362253:389:20)
id: Bayes Chrome
Approximately 10/21/2018, 10:00:35 PM
```

**Comment by KatieWoe** [comment]
Also found in mixed numbers
```
fractions-mixed-numbers : fuzz : require.js : run
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/assert/js/assert.js:22:13)
    at arrayRemove (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/phet-core/js/arrayRemove.js?bust=1540307505447:22:15)
    at FractionChallengeNode.removeShapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/fractions-common/js/game/view/FractionChallengeNode.js?bust=1540307505447:347:7)
    at ObservableArray._fireItemRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/axon/js/ObservableArray.js?bust=1540307505447:161:18)
    at ObservableArray.remove (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/axon/js/ObservableArray.js?bust=1540307505447:201:14)
    at Animator.shapePiece.animator.animateTo [as endAnimationCallback] (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/fractions-common/js/building/model/BuildingModel.js?bust=1540307505447:149:32)
    at Animator.endAnimation (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/fractions-common/js/building/model/Animator.js?bust=1540307505447:111:14)
    at Animator.step (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/fractions-common/js/building/model/Animator.js?bust=1540307505447:119:16)
    at ShapePiece.step (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/fractions-common/js/building/model/ShapePiece.js?bust=1540307505447:110:21)
    at activeShapePieces.forEach.shapePiece (https://bayes.colorado.edu/continuous-testing/snapshot-1540305163088/fractions-common/js/building/model/BuildingModel.js?bust=1540307505447:389:20)
id: Bayes Chrome
Approximately 10/23/2018, 8:32:43 AM
```

**Comment by jonathanolson** [comment]
I believe these failures should be fixed. Can you verify (or see if they don't happen in CT for a bit?)

**Comment by KatieWoe** [comment]
@jonathanolson saw it once yesterday in mixed-numbers, but otherwise it looks clear.

**Comment by jonathanolson** [comment]
This should be fixed in master.

**Comment by KatieWoe** [comment]
Closing
